# Generated by Django 6.1 on 2026-08-15 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "price_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Overrides the listing's own price_per_day for this date when set.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("units_available", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Rental availabilities",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="RentalOperator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=70, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "cancellation_policy",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "refund_policy",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivating an operator also deactivates all of their listings, hiding them from the public API.",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "verified"],
            },
        ),
        migrations.CreateModel(
            name="RentalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated booking reference number",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated 4-digit code, shown once at booking creation. Paired with `number` as an alternative to `number` + `email` for the guest booking lookup endpoint.",
                        max_length=4,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WAITING_PAYMENT", "Awaiting Payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("PARTIAL_PAYMENT", "Partial Payment"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="django_rentals.rentalavailability",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for guest bookings.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("VEHICLE", "Vehicle"), ("GEAR", "Gear")],
                        default="VEHICLE",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price_per_day",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="PUBLISHED",
                        help_text="Editorial state (draft/published) - independent of is_active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="Operator responsible for this listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="django_rentals.rentaloperator",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="django_rentals.rentallisting",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="rentalavailability",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="django_rentals.rentallisting",
            ),
        ),
    ]
