# Generated by Django 5.2.17 on 2026-08-21 12:40
# pylint:disable=line-too-long

import django.db.models.deletion
import swapper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rentals', '0001_initial'),
        swapper.dependency('django_rentals', 'Location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, null=True, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'swappable': 'DJANGO_RENTALS_LOCATION_MODEL',
            },
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Structured location, backfilled from `city` (P9.4) - `city` stays in place until after destipak's own swap+reconcile (P9.5/P9.6) lands.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.DJANGO_RENTALS_LOCATION_MODEL),
        ),
    ]
