# Generated by Django 5.2.17 on 2026-08-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rentals', '0003_backfill_location_from_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentallisting',
            name='city',
        ),
        migrations.AlterField(
            model_name='rentallisting',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Structured location for this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.DJANGO_RENTALS_LOCATION_MODEL),
        ),
    ]
